name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  # 编译和构建 Docker Image
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 登录 Docker Registry
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 构建 Docker 镜像 (使用 buildx 语法 )
      - name: Build Docker image
        run: |
          docker buildx build \
            --cache-from type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/hello-world:latest \
            -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/hello-world:latest \
            --load \
            .

      # 4. 推送 Docker 镜像
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/hello-world:latest

  # 重新部署 Image
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 5.1. 登录 TX_SG_01 服务器重新部署
      - name: Executing remote ssh commands on tx_sg_01 server using private key
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.TX_SG_01_HOST }}
          port: ${{ secrets.TX_SG_01_PORT }}
          username: ${{ secrets.TX_SG_01_USERNAME }}
          key: ${{ secrets.TX_SG_01_KEY }}
          script: |
            cd ${{ vars.TX_SG_01_PATH }}
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans
      
      # 5.2. 登录 GC_US_01 服务器重新部署
      - name: Executing remote ssh commands on gc_us_01 server using private key
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.GC_US_01_HOST }}
          port: ${{ secrets.GC_US_01_PORT }}
          username: ${{ secrets.GC_US_01_USERNAME }}
          key: ${{ secrets.GC_US_01_KEY }}
          script: |
            cd ${{ vars.GC_US_01_PATH }}
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans

      # 5.3. 登录 DM_US_01 服务器重新部署
      - name: Executing remote ssh commands on dm_us_01 server using private key
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DM_US_01_HOST }}
          port: ${{ secrets.DM_US_01_PORT }}
          username: ${{ secrets.DM_US_01_USERNAME }}
          key: ${{ secrets.DM_US_01_KEY }}
          script: |
            cd ${{ vars.DM_US_01_PATH }}
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans